YcuhForum/Models/Article/Article.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace YcuhForum.Models
{
    public class Article
    {
        [Key]
        public string Article_Id { get; set; }
       
        public string Article_Title { get; set; }

        public string Article_Content { get; set; }

        public int Article_Point { get; set; }

        public string Article_FileUrl { get; set; }

        public bool Article_IsShow { get; set; }

        public bool Article_IsReply { get; set; }

        public string Article_OtherSiteUrl { get; set; }

        public int Article_Count { get; set; }

        public bool Article_DelLock { get; set; }

        public DateTime Article_CreateTime { get; set; }

        public DateTime Article_UpdateTime { get; set; }

        public string Article_FK_UpdateUserId { get; set; }

        public string Article_FK_UserId { get; set; }

        public string Article_FK_ArticleGroupId { get; set; }

        public string Article_FK_PointCategoryId { get; set; }

        
        public Article()
        {
            Article_Id = Guid.NewGuid().ToString();
            Article_Title = string.Empty;
            Article_Content = string.Empty;
            Article_FileUrl = string.Empty;
            Article_OtherSiteUrl = string.Empty;
            Article_IsShow = true;
            Article_IsReply = true;
            Article_CreateTime = DateTime.Now;
            Article_UpdateTime = DateTime.Now;
            Article_Count = 0;
            Article_Point = 0;
            Article_FK_ArticleGroupId = string.Empty;
            Article_FK_PointCategoryId = string.Empty;
        }
   
    }

}

YcuhForum/Models/Article/ArticleManager.cs
using AutoMapper;
using PagedList;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace YcuhForum.Models
{
    public class ArticleManager
    {
        private static List<Article> _ArticleCache = new List<Article>();
        private static object _ArticleQueueLock = new Object();

        #region 初始化
        public static void Initial()
        {
            using (ApplicationDbContext db = new ApplicationDbContext())
            {
                _ArticleCache = db.Articles.AsNoTracking().Where(a=>!a.Article_DelLock).ToList();
            }
        }
        #endregion

        #region 基本操作 (db & cache)
        //取得所有記錄
        public static List<Article> GetAll()
        {
            return _ArticleCache.OrderBy(t => t.Article_CreateTime).ToList();
        }

        //分頁
        public static IPagedList<Article> GetPagedList(int pageNumber, int pageSize)
        {
            return _ArticleCache.OrderBy(a => a.Article_CreateTime).ToPagedList(pageNumber, pageSize);
        }

        //透過Id取得記錄
        public static Article Get(string id)
        {
            return _ArticleCache.FirstOrDefault(p => p.Article_Id == id);
        }

        //新增單一記錄
        public static void Create(Article article)
        {
            Create(new List<Article>() { article });
        }

        //新增多筆記錄
        public static void Create(List<Article> articles)
        {
            //更新資料庫
            using (ApplicationDbContext db = new ApplicationDbContext())
            {
                lock (_ArticleQueueLock)
                {
                    db.Articles.AddRange(articles);
                    db.SaveChanges();
                    //更新記憶体
                    _ArticleCache.AddRange(articles);
                }
            }
        }

        //更新一筆記錄
        public static void Update(Article articles)
        {
            Update(new List<Article>() { articles });
        }

        //更新多筆記錄
        public static void Update(List<Article> articles)
        {
            //更新資料庫
            using (ApplicationDbContext db = new ApplicationDbContext())
            {
                var objIDs = articles.Select(a => a.Article_Id).ToList();
                var objInDB = db.Articles.Where(a => objIDs.Contains(a.Article_Id)).ToList();

                foreach (Article item in objInDB)
                {
                    var theNewFromOutside = articles.FirstOrDefault(a => a.Article_Id == item.Article_Id);

                    item.Article_FK_PointCategoryId = theNewFromOutside.Article_FK_PointCategoryId;

                    item.Article_Content = theNewFromOutside.Article_Content;

                    item.Article_DelLock = theNewFromOutside.Article_DelLock;

                    item.Article_FileUrl = theNewFromOutside.Article_FileUrl;

                    item.Article_FK_ArticleGroupId = theNewFromOutside.Article_FK_ArticleGroupId;

                    item.Article_IsReply = theNewFromOutside.Article_IsReply;

                    item.Article_IsShow = theNewFromOutside.Article_IsShow;
                    
                    item.Article_OtherSiteUrl = theNewFromOutside.Article_OtherSiteUrl;

                    item.Article_Title = theNewFromOutside.Article_Title;

                    item.Article_UpdateTime = DateTime.Now;


                }

                lock (_ArticleQueueLock)
                {
                    db.SaveChanges();
                   
                    //更新記憶体
                    _ArticleCache.RemoveAll(a => objIDs.Contains(a.Article_Id));
                    _ArticleCache.AddRange(articles);
                }
            }
        }

        //刪除一筆記錄
        public static void Remove(Article article)
        {
            Remove(new List<Article>() { article });
        }

        //刪除多筆記錄
        public static void Remove(List<Article> articles)
        {
            //更新資料庫
            using (ApplicationDbContext db = new ApplicationDbContext())
            {
                var objIDs = articles.Select(a => a.Article_Id).ToList();
                var objInDB = db.Articles.Where(a => objIDs.Contains(a.Article_Id)).ToList();

                foreach (var item in objInDB)
                {
                    item.Article_DelLock = true;
                }

                lock (_ArticleQueueLock)
                {
                    db.SaveChanges();

                    //更新記憶体
                    _ArticleCache.RemoveAll(a => objIDs.Contains(a.Article_Id));
                }
            }
        }
        #endregion

        #region Domain & ViewModel 映射

        public static ArticleModel DomainToModel(Article Article)
        {
            ArticleModel viewModel = new ArticleModel();
            Mapper.CreateMap<Article, ArticleModel>();
            viewModel = Mapper.Map<Article, ArticleModel>(Article);

            return viewModel;
        }

        public static Article ModelToDomain(ArticleModel viewModel)
        {
            Article Article = new Article();

            try
            {
                Mapper.CreateMap<ArticleModel, Article>();
                Article = Mapper.Map<ArticleModel, Article>(viewModel);
            }
            catch(Exception e)
            {

            }
          

            return Article;
        }

        public static List<ArticleModel> DomainToModel(List<Article> articleModel)
        {
            List<ArticleModel> viewModel = new List<ArticleModel>();
            Mapper.CreateMap<List<Article>, List<ArticleModel>>();
            viewModel = Mapper.Map<List<Article>, List<ArticleModel>>(articleModel);

            return viewModel;
        }


        #endregion

        #region 進階查詢
        public static List<Article> getArticleByUser(List<string> groupList)
        {
            return _ArticleCache.Where(a => groupList.Any(b => a.Article_FK_ArticleGroupId == b) && a.Article_IsShow && !a.Article_DelLock).OrderByDescending(a => a.Article_CreateTime).ToList();
        }

        public static List<Article> getArticleByTime()
        {
            return _ArticleCache.OrderByDescending(a => a.Article_CreateTime).Take(5).ToList();
        }

        public static List<Article> getArticleByGroup()
        {
            return _ArticleCache.GroupBy(a => a.Article_FK_ArticleGroupId).OrderByDescending(b => b.OrderByDescending(c => c.Article_CreateTime)).SelectMany(b => b).ToList();
        }

        public static IPagedList<Article> getArticleByGroupId(string id, int pageNumber, int pageSize)
        {
            return _ArticleCache.Where(a => a.Article_FK_ArticleGroupId == id).OrderByDescending(a => a.Article_CreateTime).ToPagedList(pageNumber, pageSize);
        }

        #endregion
    }
}

YcuhForum/Models/Article/ArticleModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace YcuhForum.Models
{
    public class ArticleModel
    {
        public string Article_Id { get; set; }

        [Required]
        [Display(Name = "文章標題")]
        public string Article_Title { get; set; }

        [Display(Name = "文章內容")]
        public string Article_Content { get; set; }

        public int Article_Point { get; set; }

        //[StringLength(10,MinimumLength=5)]
        //[Remote("CheckObj", "Validate", ErrorMessage = "遠端驗證失敗")]
        public string Article_FileUrl { get; set; }

        [Display(Name = "是否公開/發布")]
        public bool Article_IsShow { get; set; }

        [Display(Name = "是否開放回覆")]
        public bool Article_IsReply { get; set; }

        [Display(Name = "外部連結")]
        public string Article_OtherSiteUrl { get; set; }

        public bool Article_DelLock { get; set; }

        public DateTime Article_CreateTime { get; set; }

        public DateTime Article_UpdateTime { get; set; }

        public string Article_FK_UpdateUserId { get; set; }

        public string Article_FK_UserId { get; set; }

        public string Article_FK_ArticleGroupId { get; set; }

        [Display(Name = "文章類型")]
        public string Article_FK_PointCategoryId { get; set; }

        #region 畫面所需其他表部分資料

        public string Article_UserJobTitle { get; set; }

        public string Article_ArticleGroupName { get; set; }

        public string Article_PointCategoryName { get; set; }
        #endregion

        public ArticleModel()
        {
            Article_Id = Guid.NewGuid().ToString();
            Article_Title = string.Empty;
            Article_Content = string.Empty;
            Article_FileUrl = string.Empty;
            Article_OtherSiteUrl = string.Empty;
            Article_IsShow = true;
            Article_IsReply = true;
            Article_CreateTime = DateTime.Now;
            Article_UpdateTime = DateTime.Now;
        }
    }
}

YcuhForum/Controllers/ArticleController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using YcuhForum.Models;

namespace YcuhForum.Controllers
{
    public class ArticleController : Controller
    {
        public ActionResult List()
        {
            return View();
        }

        public ActionResult Content()
        {
            return View();
        }

        public ActionResult Reply()
        {
            return PartialView("_Reply");
        }

        public ActionResult Test()
        {
            return PartialView("_Test");
        }

        /// <summary>
        /// 新增文章
        /// </summary>
        /// <returns></returns>
        public ActionResult Create()
        {
            ArticleModel model = new ArticleModel();
            ViewBag.PointCategorySelector = PreparePointCategorySelectList(null);
            //ViewBag.ArticleGroupSelector = PrepareUserList();

            return View(model);
        }

        /// <summary>
        /// 編輯文章
        /// </summary>
        /// <returns></returns>
        public ActionResult Edit()
        {
            ViewBag.PointCategorySelector = PreparePointCategorySelectList(null);
            //ViewBag.ArticleGroupSelector = PrepareUserList();
            return View();
        }

        #region 下拉選單
        private List<SelectListItem> PreparePointCategorySelectList(string selectedPointCategoryId)
        {
            var pointCategory = PointCategoryManager.GetAll();
            List<SelectListItem> pointSeletor = new List<SelectListItem>();
            foreach (var item in pointCategory)
            {
                pointSeletor.Add(new SelectListItem()
                {
                    Text = item.PointCategory_Name,
                    Value = item.PointCategory_Id.ToString(),
                    Selected = (item.PointCategory_Id == selectedPointCategoryId)
                });
            }
            return pointSeletor;
        }

        private List<SelectListItem> PrepareArticleGroupSelectList(string selectedArticleGroupId)
        {
            var articleGroup = ArticleGroupManager.GetAll();
            List<SelectListItem> articleGroupSeletor = new List<SelectListItem>();
            foreach (var item in articleGroup)
            {
                articleGroupSeletor.Add(new SelectListItem()
                {
                    Text = item.ArticleGroup_Name,
                    Value = item.ArticleGroup_Id.ToString(),
                    Selected = (item.ArticleGroup_Id == selectedArticleGroupId)
                });
            }
            return articleGroupSeletor;
        }

        private MultiSelectList PrepareUserList()
        {
            var userObjList = AUManager.GetAll();

            return new MultiSelectList(userObjList, "Id", "ApplicationUser_Name", new List<string>());
        }
        #endregion
    }
}

YcuhForum/Controllers/BackendCkeditorController.cs
using System;
using System.IO;
using System.Web;
using System.Web.Mvc;

namespace YcuhForum.Controllers
{
    public class BackendCkeditorController : BaseController
    {
        /// <summary>
        /// 編輯器圖片上傳
        /// </summary>
        /// <param name="upload"></param>
        /// <param name="CKEditorFuncNum"></param>
        /// <param name="CKEditor"></param>
        /// <param name="langCode"></param>
        /// <returns></returns>
        [HttpPost]
        public ActionResult Uploadp(HttpPostedFileBase upload, string CKEditorFuncNum, string CKEditor, string langCode)
        {
            string result = "";
            if (upload != null && upload.ContentLength > 0)
            {
                //儲存圖片至Server
                upload.SaveAs(Server.MapPath("~/Upload/image/" + upload.FileName));

                var imageUrl = Url.Content("~/Upload/image/" + upload.FileName);
                var vMessage = string.Empty;

                result = @"<html><body><script>window.parent.CKEDITOR.tools.callFunction(" + CKEditorFuncNum + ", \"" + imageUrl + "\", \"" + vMessage + "\");</script></body></html>";

            }

            return Content(result);
        }

    }
}

YcuhForum/Views/Article/Content.cshtml
@{
    ViewBag.Title = "文章內容";
}

<div class="row">
    <div class="table-area">
        <div class="table-tag-group">
            <a href="@Url.Action("List", "Article")">全部</a>
            <a href="@Url.Action("List", "Article")">傷檢</a>
            <a href="@Url.Action("List", "Article")">領藥</a>
            <a href="@Url.Action("List", "Article")">公文</a>
            <a href="@Url.Action("List", "Article")">醫學</a>
        </div>
        <div class="table-page">
            <a class="table-back" href="@Url.Action("List", "Article")">回列表</a>
            <a class="table-reply" href="javascript:void(0)"></a>
        </div>
        <div class="table-title">
            <img src="~/Img/tag.png" />
            <a href="@Url.Action("Index", "Home")">首頁</a> > <a href="@Url.Action("List", "Article")">醫管部</a> > 公文
        </div>
        <table border="0" cellpadding="0" cellspacing="0" class="table-form">
            <tr>
                <td rowspan="2" width="150">
                    <h2 class="name">副院長</h2>
                    <p class="info">
                        <img src="~/Img/cycle.png" class="table-cycle" />
                        院內單位
                    </p>
                    <p class="info">
                        註冊日期：<br />
                        &nbsp;&nbsp;
                        2015/12/23
                    </p>
                </td>
                <td height="20">
                    <h2 class="article-title">衛福部中央健保署健康存摺系統推廣</h2>
                    <div class="btn-area">
                        <a class="btn-edit" href="@Url.Action("Edit", "Article")">編輯</a>
                        <a class="btn-delete" href="javascript:void(0)">刪除</a>
                    </div>
                </td>
            </tr>
            <tr>
                <td>
                    <div class="video">
                        <iframe width="400" height="250" src="https://www.youtube.com/embed/LbDizRI5wrA" frameborder="0" allowfullscreen></iframe>
                    </div>
                    <div class="ckeditor-content">
                        <p>
                            教育部函轉衛生福利部函以，為加強國人自我健康管理，請鼓勵同仁使用該部中央健康保險署<br />
                            「健康存摺」系統，詳情如附。<a href="https://med.nhi.gov.tw/ihke0000/IHKE0100S01.aspx" target="_blank">https://med.nhi.gov.tw/ihke0000/IHKE0100S01.aspx</a>
                        </p>
                    </div>
                    <div class="append-area">
                        <div class="file">附加檔案：<a href="#">健康存摺.doc</a></div>
                        <div class="count">觀看次數：184</div>
                    </div>
                    <div class="function">
                        <div class="create-date">發表於 2015/12/23 14:20</div>
                        <div class="function-btn">
                            <div class="table-checkbox"><input type="checkbox" /><div class="checkbox-text">已閱讀此文章</div></div>
                            <a class="table-test" href="javascript:void(0)"></a>
                            <a class="table-reply-article" href="javascript:void(0)"></a>
                        </div>
                    </div>
                </td>
            </tr>
            <tr>
                <td class="reply-title">
                    回覆
                </td>
                <td class="reply-content">
                    @for (int i = 0; i < 3; i++)
                    {
                        <div class="reply-content-item">
                            <h2>副院長</h2>
                            <div class="item-content">
                                <span>：</span>
                                請各位同仁一定要閱讀!!
                            </div>
                            <div class="item-date">
                                2015/12/23 14:30
                            </div>
                        </div>
                    }
                </td>
            </tr>
        </table>
        @for (int j = 1; j < 4; j++)
        {
            <table border="0" cellpadding="0" cellspacing="0" class="table-form">
                <tr>
                    <td rowspan="2" width="150">
                        <h2 class="name">護理長</h2>
                        <p class="info">
                            <img src="~/Img/cycle.png" class="table-cycle" />
                            護理單位
                        </p>
                        <p class="info">
                            註冊日期：<br />
                            &nbsp;&nbsp;
                            2015/12/23
                        </p>
                    </td>
                    <td height="20">
                        <h2 class="article-title">RE：衛福部中央健保署健康存摺系統推廣</h2>
                        <div class="level">
                            #@(j)
                        </div>
                    </td>
                </tr>
                <tr>
                    <td>
                        <div class="ckeditor-content">
                            <p>
                                好文章值得推~~~~
                            </p>
                        </div>
                        <div class="append-area">
                        </div>
                        <div class="function">
                            <div class="create-date">回覆於 2015/12/23 14:20</div>
                            <div class="function-btn">
                                <a class="table-reply-article" href="javascript:void(0)"></a>
                            </div>
                        </div>
                    </td>
                </tr>
                <tr>
                    <td class="reply-title">
                        回覆
                    </td>
                    <td class="reply-content">
                        @for (int i = 0; i < 3; i++)
                        {
                            <div class="reply-content-item">
                                <h2>副院長</h2>
                                <div class="item-content">
                                    <span>：</span>
                                    請各位同仁一定要閱讀!!
                                </div>
                                <div class="item-date">
                                    2015/12/23 14:30
                                </div>
                            </div>
                        }
                    </td>
                </tr>
            </table>
        }
        <div class="table-page">
            <a class="table-back" href="@Url.Action("List", "Article")">回列表</a>
            <a class="table-reply" href="javascript:void(0)"></a>
        </div>
    </div>

    <!-- 回覆文章 -->
    @Html.Action("Reply")

    <!-- 文章測驗 -->
    @Html.Action("Test")
</div>

@section Scripts{
    <script>
        //回覆文章
        $(".table-reply, .table-reply-article").click(function () {
            $('#replyModel').swpmodal({
                //openEffect: { speed: 500 },
                //closeEffect: { speed: 500 },
                closeOnEsc: false,
                closeOnOverlayClick: false,
                beforeOpen: function (data, el) {
                    var editor = CKEDITOR.instances['ArticleUserReplay_Content'];
                    if (editor) {
                        CKEDITOR.instances['ArticleUserReplay_Content'].destroy(true);
                    }
                    CKEDITOR.replace('ArticleUserReplay_Content', { filebrowserImageUploadUrl: '@Url.Action("Uploadp", "BackendCkeditor", new { Area = "" })' });
                },
                afterOpen: function (data, el) {

                },
                beforeClose: function (data, el) {

                },
                afterClose: function (data, el) {

                }
            });
        })

        //文章測驗
        $(".table-test").click(function () {
            $('#testModel').swpmodal({
                //openEffect: { speed: 500 },
                //closeEffect: { speed: 500 },
                closeOnEsc: false,
                closeOnOverlayClick: false,
                beforeOpen: function (data, el) {
                    
                },
                afterOpen: function (data, el) {

                },
                beforeClose: function (data, el) {

                },
                afterClose: function (data, el) {

                }
            });
        })
    </script>
}

YcuhForum/Views/Article/Create.cshtml
@model YcuhForum.Models.ArticleModel
@{
    ViewBag.Title = "新增文章";
}

<div class="row">
    <div class="table-area">
        <div class="table-tag-group">
            <a href="@Url.Action("List", "Article")">全部</a>
            <a href="@Url.Action("List", "Article")">傷檢</a>
            <a href="@Url.Action("List", "Article")">領藥</a>
            <a href="@Url.Action("List", "Article")">公文</a>
            <a href="@Url.Action("List", "Article")">醫學</a>
        </div>

        @using (Html.BeginForm("Create", "Article", FormMethod.Post, new { id = "targetForm" }))
        {
            <div class="table-page">
                <a class="table-back" href="@Url.Action("List", "Article")">回列表</a>
                <a class="table-save" href="javascript:void(0)"></a>
            </div>
            <div class="table-title">
                <img src="~/Img/tag.png" />
                <a href="@Url.Action("Index", "Home")">首頁</a> > <a href="@Url.Action("List", "Article")">醫管部</a> > @ViewBag.Title
            </div>

            <div class="form-horizontal edit-form">
                @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                @Html.HiddenFor(model => model.Article_Id)
                @Html.HiddenFor(model => model.Article_FK_UserId)

                @*<div class="form-group">
                    @Html.Label("人員", htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.ListBox("userIdList", (IEnumerable<SelectListItem>)ViewBag.ArticleGroupSelector, new { @class = "form-control" })
                    </div>
                </div>*@

                <div class="form-group">
                    @Html.LabelFor(model => model.Article_Title, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.Article_Title, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.Article_Title, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.Article_FK_PointCategoryId, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.DropDownListFor(model => model.Article_FK_PointCategoryId, (IEnumerable<SelectListItem>)ViewBag.PointCategorySelector, "請選擇", new { @class = "form-control" })
                        @Html.ValidationMessageFor(model => model.Article_FK_PointCategoryId, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.Article_Content, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.TextAreaFor(model => model.Article_Content, new { @class = "ckeditor" })
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.Article_OtherSiteUrl, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.Article_OtherSiteUrl, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.Article_OtherSiteUrl, "", new { @class = "text-danger" })
                    </div>
                </div>

                @*<div class="form-group">
                    @Html.LabelFor(model => model.Article_FileUrl, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.Article_FileUrl, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.Article_FileUrl, "", new { @class = "text-danger" })
                    </div>
                </div>*@

                <div class="form-group">
                    @Html.LabelFor(model => model.Article_IsShow, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        <div class="checkbox">
                            @Html.EditorFor(model => model.Article_IsShow, new { htmlAttributes = new { @class = "form-control" } })
                            @Html.ValidationMessageFor(model => model.Article_IsShow, "", new { @class = "text-danger" })

                        </div>
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.Article_IsReply, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        <div class="checkbox">
                            @Html.EditorFor(model => model.Article_IsReply, new { htmlAttributes = new { @class = "form-control" } })
                            @Html.ValidationMessageFor(model => model.Article_IsReply, "", new { @class = "text-danger" })
                        </div>
                    </div>
                </div>

                @*<div class="form-group">
                    @Html.LabelFor(model => model.Article_DelLock, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        <div class="checkbox">
                            @Html.EditorFor(model => model.Article_DelLock, new { htmlAttributes = new { @class = "form-control" } })
                            @Html.ValidationMessageFor(model => model.Article_DelLock, "", new { @class = "text-danger" })
                        </div>
                    </div>
                </div>*@
            </div>

            <div class="table-page">
                <a class="table-back" href="@Url.Action("List", "Article")">回列表</a>
                <a class="table-save" href="javascript:void(0)"></a>
            </div>
        }
    </div>
</div>

@section Scripts{
    <script>
        CKEDITOR.replace('Article_Content', { filebrowserImageUploadUrl: '@Url.Action("Uploadp", "BackendCkeditor", new { Area = "" })' });

        $(".table-save").click(function () {
            $("#targetForm").submit();
        })
    </script>
}

YcuhForum/Views/Article/_Reply.cshtml
@model YcuhForum.Models.ArticleUserReplayModel

<div class="form-hidden">
    <div class="form-horizontal box-modal" id="replyModel">
        <div class="box-modal_close swpmodal-close">&times;</div>
        <h2>回覆文章</h2>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.ArticleUserReplay_FK_ArticleId)
        @Html.HiddenFor(model => model.ArticleUserReplay_FK_UserId)
        @Html.HiddenFor(model => model.ArticleUserReplay_ParentId)

        <div class="form-group">
            <div class="col-md-12">
                RE：衛福部中央健保署健康存摺系統推廣
            </div>
        </div>

        <div class="form-group hasReply">
            <div class="col-md-12">
                護理長 回覆於 2015/12/23 14:20
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-12">
                @Html.TextAreaFor(model => model.ArticleUserReplay_Content, new { @class = "ckeditor" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-12 text-right">
                <input type="button" value="回覆文章" class="btn-edit reply" />
            </div>
        </div>
    </div>
</div>