YcuhForum/Controllers/BackendArticleController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using YcuhForum.Models;
using YcuhForum.Helper;

namespace YcuhForum.Controllers
{
    [ICDTAuthorize("Admin")]
    public class BackendArticleController : BaseController
    {

        public ActionResult Index(int page = 1)
        {
            return View(ArticleManager.GetPagedList(page, 10));
        }


        public ActionResult Create()
        {
            ViewBag.Action = "Create";            
            ArticleModel model = new ArticleModel();
            ViewBag.PointCategorySelector = PreparePointCategorySelectList(null);
            ViewBag.ArticleGroupSelector = PrepareUserList();
           // ViewBag.ArticleGroupSelector = PrepareArticleGroupSelectList(null);
            return PartialView("_Create", model);
        }

       
        [HttpPost]
        [ValidateInput(false)]
        [AjaxValidateAntiForgeryTool]
        public ActionResult Create(ArticleModel articleModel,List<string> userIdList)
        {
            if(ModelState.IsValid)
            {
                try
                {
                    #region 文章
                    //更新時間
                    articleModel.Article_CreateTime = DateTime.Now;
                    articleModel.Article_UpdateTime = DateTime.Now;
                    Article articleObj = ArticleManager.ModelToDomain(articleModel);
                    ArticleManager.Create(articleObj);
                    #endregion

                    #region 指定觀看(阿長有選或沒選(同一般者行為))
                    if (userIdList != null && userIdList.Count >= 0)
                    {
                        SetEnforce(articleObj.Article_Id, userIdList);
                    }

                    #endregion
                    return RedirectToAction("Index");
                }
                catch (Exception e)
                {
                    ErrorRecord newErrorRecord = new ErrorRecord();
                    newErrorRecord.ErrorRecord_SystemMessage = e.Message;
                    newErrorRecord.ErrorRecord_ActionDescribe = "文章新增異常";
                    var actionStr = "建立者:" + strUserId + ";" + Newtonsoft.Json.JsonConvert.SerializeObject(articleModel);
                    newErrorRecord.ErrorRecord_CustomedMessage = actionStr;
                    ErrorTool.RecordByDB(newErrorRecord);
                    return RedirectToAction("Index");
                }
            }
            else
            {
                ViewBag.PointCategorySelector = PreparePointCategorySelectList(null);
                ViewBag.ArticleGroupSelector = PrepareUserList();
                return PartialView("_Create", articleModel);
            }
            
        }

     
        public string Edit(string id)
        {
            ViewBag.Action = "Edit";
            var targetObj =  ArticleManager.DomainToModel(ArticleManager.Get(id));
            ViewBag.PointCategorySelector = PreparePointCategorySelectList(targetObj.Article_FK_PointCategoryId);
           //ViewBag.ArticleGroupSelector = PrepareArticleGroupSelectList(targetObj.Article_FK_ArticleGroupId);
           return Helper.RenderPartialTool.RenderPartialViewToString(this, "_Create", targetObj);

        }

     
        [HttpPost]
        [ValidateInput(false)]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(ArticleModel articleModel, List<string> userIdList)
        {
            try
            {
                #region 文章修改
                var articleObj = ArticleManager.ModelToDomain(articleModel);
                ArticleManager.Update(articleObj);
                #endregion

                #region 修改指定觀看(若已觀看則不處理)
                if (userIdList != null && userIdList.Count >= 0)
                {
                    UpdateEnforce(articleObj.Article_Id, userIdList);
                }
             
                #endregion

                return RedirectToAction("Index");
            }
            catch(Exception e)
            {
                ErrorRecord newErrorRecord = new ErrorRecord();
                newErrorRecord.ErrorRecord_SystemMessage = e.Message;
                newErrorRecord.ErrorRecord_ActionDescribe = "文章修改異常";
                var actionStr = "建立者:" + strUserId + ";" + Newtonsoft.Json.JsonConvert.SerializeObject(articleModel);
                newErrorRecord.ErrorRecord_CustomedMessage = actionStr;
                ErrorTool.RecordByDB(newErrorRecord);
                return RedirectToAction("Index");
            }
        }

       
        [HttpPost]
        public ActionResult Delete(string id)
        {
            try
            {
                ArticleManager.Remove(ArticleManager.Get(id));

                return new HttpStatusCodeResult(System.Net.HttpStatusCode.OK);
            }
            catch
            {
                return new HttpStatusCodeResult(System.Net.HttpStatusCode.BadRequest);
            }
        }

        #region 下拉選單
        private List<SelectListItem> PreparePointCategorySelectList(string selectedPointCategoryId)
        {
            var pointCategory = PointCategoryManager.GetAll();
            List<SelectListItem> pointSeletor = new List<SelectListItem>();
            foreach (var item in pointCategory)
            {
                pointSeletor.Add(new SelectListItem()
                {
                    Text = item.PointCategory_Name,
                    Value = item.PointCategory_Id.ToString(),
                    Selected = (item.PointCategory_Id == selectedPointCategoryId)
                });
            }
            return pointSeletor;
        }

        private List<SelectListItem> PrepareArticleGroupSelectList(string selectedArticleGroupId)
        {
            var articleGroup = ArticleGroupManager.GetAll();
            List<SelectListItem> articleGroupSeletor = new List<SelectListItem>();
            foreach (var item in articleGroup)
            {
                articleGroupSeletor.Add(new SelectListItem()
                {
                    Text = item.ArticleGroup_Name,
                    Value = item.ArticleGroup_Id.ToString(),
                    Selected = (item.ArticleGroup_Id == selectedArticleGroupId)
                });
            }
            return articleGroupSeletor;
        }

        private MultiSelectList PrepareUserList()
        {
            var userObjList = AUManager.GetAll();

            return new MultiSelectList(userObjList, "Id", "ApplicationUser_Name", new List<string>());
        }
        #endregion


        #region 觀看者指定修改

        private void SetEnforce(string articleId, List<string> userIdList)
        {
            try
            {
                List<ArticleUserRecord> articleUserRecord = new List<ArticleUserRecord>();
                for (int i = 0; i < userIdList.Count; i++)
                {
                    ArticleUserRecord tempArticleUserRecord = new ArticleUserRecord();
                    tempArticleUserRecord.ArticleUserRecord_Id = Guid.NewGuid().ToString();
                    tempArticleUserRecord.ArticleUserRecord_CreateTime = DateTime.Now;
                    tempArticleUserRecord.ArticleUserRecord_UpdateTime = new DateTime();
                    tempArticleUserRecord.ArticleUserRecord_FK_ArticleId = articleId;
                    tempArticleUserRecord.ArticleUserRecord_FK_UserId = userIdList[i];
                    articleUserRecord.Add(tempArticleUserRecord);
                }
                ArticleUserRecordManager.Create(articleUserRecord);
            }
            catch (Exception e)
            {
                ErrorRecord newErrorRecord = new ErrorRecord();
                newErrorRecord.ErrorRecord_SystemMessage = e.Message;
                newErrorRecord.ErrorRecord_ActionDescribe = "指定觀看新增異常";
                var userStr = Newtonsoft.Json.JsonConvert.SerializeObject(userIdList);
                var actionStr = "目標文章:" + articleId + "目標資料:" + userStr;
                newErrorRecord.ErrorRecord_CustomedMessage = actionStr;
                ErrorTool.RecordByDB(newErrorRecord);
            }
          
        }

        private void UpdateEnforce(string articleId, List<string> userIdList)
        {
            try
            {
                List<ArticleUserRecord> articleUserRecordRemoveList = new List<ArticleUserRecord>();
                List<ArticleUserRecord> articleUserRecordCreteList = new List<ArticleUserRecord>();
                var userEnforceList = ArticleUserRecordManager.getEnforceUser(articleId);
                //有比對到就刪除,沒有就新增
                foreach (var item in userIdList)
                {
                    var targetObj = userEnforceList.Where(a => userIdList.Any(b => b == a.ArticleUserRecord_FK_UserId)).FirstOrDefault();
                    if (targetObj == null)
                    {
                        ArticleUserRecord newArticleUserRecord = new ArticleUserRecord();
                        newArticleUserRecord.ArticleUserRecord_FK_ArticleId = articleId;
                        newArticleUserRecord.ArticleUserRecord_FK_UserId = item;
                        newArticleUserRecord.ArticleUserRecord_CreateTime = DateTime.Now;
                        newArticleUserRecord.ArticleUserRecord_UpdateTime = DateTime.Now;
                        newArticleUserRecord.ArticleUserRecord_IsEnforce = true;
                        articleUserRecordCreteList.Add(newArticleUserRecord);
                    }
                    else
                    {
                        articleUserRecordRemoveList.Add(targetObj);
                    }
                }
            }
            catch (Exception e)
            {
                ErrorRecord newErrorRecord = new ErrorRecord();
                newErrorRecord.ErrorRecord_SystemMessage = e.Message;
                newErrorRecord.ErrorRecord_ActionDescribe = "指定觀看修改異常";
                var userStr = Newtonsoft.Json.JsonConvert.SerializeObject(userIdList);

YcuhForum/Controllers/BackendCkeditorController.cs
using System;
using System.IO;
using System.Web;
using System.Web.Mvc;

namespace YcuhForum.Controllers
{
    public class BackendCkeditorController : BaseController
    {
        /// <summary>
        /// 編輯器圖片上傳
        /// </summary>
        /// <param name="upload"></param>
        /// <param name="CKEditorFuncNum"></param>
        /// <param name="CKEditor"></param>
        /// <param name="langCode"></param>
        /// <returns></returns>
        [HttpPost]
        public ActionResult Uploadp(HttpPostedFileBase upload, string CKEditorFuncNum, string CKEditor, string langCode)
        {
            string result = "";
            if (upload != null && upload.ContentLength > 0)
            {
                //儲存圖片至Server
                upload.SaveAs(Server.MapPath("~/Upload/image/" + upload.FileName));

                var imageUrl = Url.Content("~/Upload/image/" + upload.FileName);
                var vMessage = string.Empty;

                result = @"<html><body><script>window.parent.CKEDITOR.tools.callFunction(" + CKEditorFuncNum + ", \"" + imageUrl + "\", \"" + vMessage + "\");</script></body></html>";

            }

            return Content(result);
        }

    }
}

YcuhForum/Views/BackendArticle/Index.cshtml
@model IPagedList<YcuhForum.Models.Article>

<p>
    <a href="#model" class="btn btn-default test fancybox" onclick="gogoCreate()">新增</a>
</p>
<table class="table">
    <tr>
        @*<th>
            @Html.DisplayNameFor(model => model.FirstOrDefault().Article_Creater)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.FirstOrDefault().Article_Group)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.FirstOrDefault().Article_Category)
        </th>*@
        <th>
            @Html.DisplayNameFor(model => model.FirstOrDefault().Article_Title)
        </th>
      
        <th>
            @Html.DisplayNameFor(model => model.FirstOrDefault().Article_FileUrl)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.FirstOrDefault().Article_IsShow)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.FirstOrDefault().Article_IsReply)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.FirstOrDefault().Article_OtherSiteUrl)
        </th>
        <th>
            考題
        </th>
        <th></th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            @*<td>
                @Html.DisplayFor(modelItem => item.Article_Creater)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Article_Group)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Article_Category)
            </td>*@
            <td>
                @Html.DisplayFor(modelItem => item.Article_Title)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Article_FileUrl)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Article_IsShow)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Article_IsReply)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Article_OtherSiteUrl)
            </td>
            <td>
                <a href="#model" class="btn btn-default test fancybox" onclick="gogoExam('@item.Article_Id')">考題</a>
            </td>
            <td>
                <a href="#model" class="btn btn-default test fancybox" onclick="gogoEdit('@item.Article_Id')">編輯</a> |

                <a href="#" class="btn btn-default test" onclick="gogoDelete('@item.Article_Id')">刪除</a>
            </td>
        </tr>
    }

</table>

<div id="model" class="model" style="display:none;width:80%" >
    @*@Html.Action("Create");*@
</div>
@Html.PagedListPager(Model, page => Url.Action("Index", new { page }))
@section header{
    <link href="~/Content/PagedList.css" rel="stylesheet" />
    <link href="~/Scripts/fancybox/css/jquery.fancybox.css" rel="stylesheet">
}
@section Scripts{
    <script src="~/Scripts/fancybox/js/jquery.fancybox.js"></script>
    
<script src="~/Scripts/jquery.validate.js"></script>
<script src="~/Scripts/jquery.validate.unobtrusive.js"></script>
    <script>
        $(function () {
            fanc();
        });
        function fanc() {
            $(".fancybox").fancybox({
                autoSize: false,
                arrows: false,
                width: '55%',
                openEffect: 'fade', //fade, elastic
                closeEffect: 'fade', //fade, elastic
                prevEffect: 'elastic',
                nextEffect: 'elastic',
                tpl: {
                    next: '<a title="下一則" class="fancybox-nav fancybox-next"><span></span></a>',
                    prev: '<a title="上一則" class="fancybox-nav fancybox-prev"><span></span></a>'
                },
                helpers: {
                    title: {
                        //inside, outside, over
                    },
                    overlay: {
                        speedIn: 0,
                        speedOut: 300,
                        opacity: 0.8,
                        css: {
                            cursor: 'default'
                        },
                        closeClick: false
                    }
                    //overlay: {
                    //    speedOut: 0
                    //}
                },
                onCleanup: function (e) {
                    e.preventDefault();
                }
            });
            /*關閉*/
            $("#close").click(function () {
                $.fancybox.close();
            });
        }

        function OpenCreate() {
            $.fancybox.open();
        }


        function gogoCreate(data) {
            $.ajax({
                type: "Get",
                url: "@Url.Action("Create", "BackendArticle")",
                success: function (data) {
                    $("#model").html(data);
                    doBack();
                    $.fancybox.open();
                },
            error: function (xhr, status) {
                alert(xhr.responseText);
            }

        });
        }


        function gogoEdit(data) {
            $.ajax({
                type: "Get",
                url: "@Url.Action("Edit", "BackendArticle")" + "?id=" + data,
                success: function (data) {

                    $("#model").html(data);
                    doBack();
                    $.fancybox.open();
                },
                error: function (xhr, status) {
                    alert(xhr.responseText);
                }

            });
        }

        function gogoDelete(data) {

            if (confirm("確定刪除?")) {

                $.ajax({
                    type: "Post",
                    url: "@Url.Action("Delete", "BackendArticle")" + "?id=" + data,
                    success: function (data) {
                        alert("刪除成功");
                        window.location.reload();
                    },
                    error: function (xhr, status) {
                        alert("系統忙碌中");
                    }

                 });
            }
            else {
                return;
            }
        }


        function gogoExam() {
            $.ajax({
                type: "Get",
                url: "@Url.Action("Exam", "BackendArticle")" + "?id=" + data,
                success: function (data) {

                    $("#model").html(data);
                    doBack();
                    $.fancybox.open();
                },
            error: function (xhr, status) {
                alert(xhr.responseText);
            }

        });
        }
        
        function doBack() {
            var editor = CKEDITOR.instances['Article_Content'];
            if (editor) {
                CKEDITOR.instances['Article_Content'].destroy();
            }
            CKEDITOR.replace('Article_Content');
        }

        function gogoNewArt() {
            $.ajax({
                type: "Post",
                url: "@Url.Action("Create", "BackendArticle")",
                headers: {
                    RequestVerificationToken : '@RazorForAjax.GetForgeryToken()'
                },
                data:$("#idForm").serialize(),
            success: function (data) {

                $("#model").html(data);
                doBack();
                $.fancybox.open();
            },
            error: function (xhr, status) {
                alert(xhr.responseText);
            }

        });
        }
        function gogoEditArt() {
            $.ajax({
                type: "Post",
                url: "@Url.Action("Create", "BackendArticle")",
               
                data: $("#idForm").serialize(),
            success: function (data) {

                $("#model").html(data);
                doBack();
                $.fancybox.open();
            },
            error: function (xhr, status) {
                alert(xhr.responseText);
            }

        });
        }
    </script>
}

YcuhForum/Views/BackendArticle/_Create.cshtml
@model YcuhForum.Models.ArticleModel



@using (Html.BeginForm((string)ViewBag.Action, "BackendArticle", FormMethod.Post))
{
  

    <div class="form-horizontal">
        <h4>Article</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.Article_Id)
        @Html.HiddenFor(model => model.Article_FK_UserId)


        @*<div class="form-group">
            @Html.LabelFor(model => model.Article_FK_ArticleGroupId, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownListFor(model => model.Article_FK_ArticleGroupId, (IEnumerable<SelectListItem>)ViewBag.ArticleGroupSelector, "請選擇", new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.Article_FK_ArticleGroupId, "", new { @class = "text-danger" })
            </div>
        </div>*@
        <div class="form-group">
            @Html.Label("人員", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.ListBox("userIdList", (IEnumerable<SelectListItem>)ViewBag.ArticleGroupSelector, new { @class = "form-control" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Article_FK_PointCategoryId, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownListFor(model => model.Article_FK_PointCategoryId, (IEnumerable<SelectListItem>)ViewBag.PointCategorySelector, "請選擇", new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.Article_FK_PointCategoryId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Article_Title, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Article_Title, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Article_Title, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Article_Content, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.TextAreaFor(model => model.Article_Content, new { @class = "ckeditor" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Article_FileUrl, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Article_FileUrl, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Article_FileUrl, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Article_IsShow, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <div class="checkbox">
                    @Html.EditorFor(model => model.Article_IsShow, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Article_IsShow, "", new { @class = "text-danger" })

                </div>
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Article_IsReply, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <div class="checkbox">
                    @Html.EditorFor(model => model.Article_IsReply, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Article_IsReply, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Article_OtherSiteUrl, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Article_OtherSiteUrl, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Article_OtherSiteUrl, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Article_DelLock, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <div class="checkbox">
                    @Html.EditorFor(model => model.Article_DelLock)
                    @Html.ValidationMessageFor(model => model.Article_DelLock, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="button" value="儲存" class="btn btn-default" onclick="gogoNewArt()"/>
            </div>
        </div>
    </div>
}

@section Scripts{
    <script>
        $(function () {
            CKEDITOR.replace('Article_Content', { filebrowserImageUploadUrl: '@Url.Action("Uploadp", "BackendCkeditor", new { Area = "" })' });
        })

    
    </script>

}